#define TIMER_COUNT 1

#define TIMER1_ENABLED  1
#define TIMER1_INSTANCE_INDEX   0

#define TIMER1_CONFIG_FREQUENCY    NRF_TIMER_FREQ_62500Hz
#define TIMER1_CONFIG_MODE         TIMER_MODE_MODE_Timer
#define TIMER1_CONFIG_BIT_WIDTH    TIMER_BITMODE_BITMODE_16Bit
#define TIMER1_CONFIG_IRQ_PRIORITY APP_IRQ_PRIORITY_LOW

#define RNG_ENABLED 1
#define RNG_CONFIG_ERROR_CORRECTION false
#define RNG_CONFIG_POOL_SIZE        16
#define RNG_CONFIG_IRQ_PRIORITY     APP_IRQ_PRIORITY_LOW
